"""admin feature

Revision ID: 1241458ae574
Revises: 331a89bf2e91
Create Date: 2020-08-13 11:54:46.192690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1241458ae574'
down_revision = '331a89bf2e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'is_control_group')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.add_column('option', sa.Column('is_control_group', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
