"""added admin dunctionality

Revision ID: 8ae108d43954
Revises: e656e9efc7ad
Create Date: 2020-08-13 15:10:08.455738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae108d43954'
down_revision = 'e656e9efc7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_column('control_group')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_group', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
