"""refactor ABOption table

Revision ID: 9e0db677ebf6
Revises: 43da8f01facc
Create Date: 2020-06-30 07:07:15.655612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0db677ebf6'
down_revision = '43da8f01facc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('is_control_group', sa.Boolean(), nullable=True))
    op.drop_column('option', 'control_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('control_group', sa.BOOLEAN(), nullable=True))
    op.drop_column('option', 'is_control_group')
    # ### end Alembic commands ###
