"""Add admin functionality

Revision ID: a1baee9dd366
Revises: a8769a888329
Create Date: 2020-08-13 11:49:57.508786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1baee9dd366'
down_revision = 'a8769a888329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'is_control_group')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.add_column('option', sa.Column('is_control_group', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
