"""add admin

Revision ID: ba0262fb27e2
Revises: 8ae108d43954
Create Date: 2020-08-13 19:55:27.884965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0262fb27e2'
down_revision = '8ae108d43954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_column('control_group')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_group', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
