"""admin feature

Revision ID: e656e9efc7ad
Revises: 1241458ae574
Create Date: 2020-08-13 11:57:06.628887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e656e9efc7ad'
down_revision = '1241458ae574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'control_group')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.add_column('option', sa.Column('control_group', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
